name: Docker Publish
on:
  workflow_call:
    inputs:
      versionTag:
        required: false
        type: string
  pull_request:
    branches:
      - master
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set semver and latest tags if release
        id: tagmeta
        run: |
          if [ "${{ github.event_name }}" = "workflow_call" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "LATEST=type=raw,value=latest" >> $GITHUB_OUTPUT
          else
            echo "LATEST=" >> $GITHUB_OUTPUT
          fi

          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "SEMVER=type=semver,pattern=${{ inputs.versionTag }}" >> $GITHUB_OUTPUT
          else
            echo "SEMVER=" >> $GITHUB_OUTPUT
          fi
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=sha
            ${{ steps.tagmeta.outputs.SEMVER }}
            ${{ steps.tagmeta.outputs.LATEST }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
